version: '3.9'

name : customer-api-service
services :
  customer-postgres :
    image: postgres:15.4
    container_name: customer-api
    ports :
      - "5422:5432"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=customer
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=customer_db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "customers_test", "-U", "customers_testuser" ]
      timeout: 5s
      interval: 2s
      retries: 3