database:
  host: localhost
  port: 5422
  name: customer_db
  username: customer
  password: 123


spring:
  application:
    name: "customer-service"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/

server:
  port: 8081
